/* TRABALHANDO COM DATAS */
/* GETDATE PEGA A DATA ATUAL */
SELECT GETDATE()
GO

/*	DATEDIFF - TRAS A DIFERENÇA ENTRE UMA DATA
	DATEDIFF(DIA/MES/ANO, COLUNA(INICIAL), COLUNA(FINAL))
*/	
SELECT NOME, DATEDIFF(DAY, NASCIMENTO, GETDATE()) AS "NASCIMENTO"
FROM ALUNO
GO

SELECT NOME, DATEDIFF(YEAR, NASCIMENTO, GETDATE()) AS "NASCIMENTO"
FROM ALUNO
GO

/* COMO O VALOR RETORNADO É UM INTEIRO, PODE SER FEITO OPERAÇÕES MATEMATICAS */
SELECT NOME, (DATEDIFF(DAY, NASCIMENTO, GETDATE())/365) AS "NASCIMENTO"
FROM ALUNO
GO

SELECT NOME, (DATEDIFF(MONTH, NASCIMENTO, GETDATE())/12) AS "NASCIMENTO"
FROM ALUNO
GO

/* DATENAME - TRAS O NOME DA DATA */
SELECT NOME, DATENAME(YEAR, NASCIMENTO)
FROM ALUNO
GO

SELECT NOME, DATENAME(MONTH, NASCIMENTO)
FROM ALUNO
GO

SELECT NOME, DATENAME(WEEKDAY, NASCIMENTO)
FROM ALUNO
GO

/* DATEPART - TRAS O VALOR INTEIRO */
SELECT NOME, DATEPART(DAY, NASCIMENTO)
FROM ALUNO
GO

SELECT NOME, DATEPART(MONTH, NASCIMENTO), DATENAME(MONTH, NASCIMENTO)
FROM ALUNO
GO

SELECT NOME, DATEPART(YEAR, NASCIMENTO)
FROM ALUNO
GO

/* DATEADD - RETORNA A DATA COM SOMA */
SELECT DATEADD(YEAR, 300, GETDATE())
GO

/* CONVERSÃO DE DADOS */

SELECT 1 + '1'
GO

SELECT '1' + '1'
GO

/* IRA RETORNAR UM ERRO POR CONTA DA CONVERSÃO IMPLICITA */
SELECT 'BANCO DE DADOS' + 1
GO

/* FUNÇÕES DE CONVERSÃO (conversão explicita) */
SELECT CAST('1' AS INT) + CAST('1' AS INT)
GO

/* IRA RETORNAR UM ERRO, POR CONTA DA TENTATIVA DE CONVERSÃO DE "/" PARA UM VALOR NÚMERICO */
SELECT NOME,
DATEPART(DAY, NASCIMENTO)+'/'+
DATEPART(MONTH, NASCIMENTO)+'/'+
DATEPART(YEAR, NASCIMENTO) AS "NASCIMENTO"
FROM ALUNO
GO

SELECT NOME,
CAST(DATEPART(DAY, NASCIMENTO) AS VARCHAR)+'/'+
CAST(DATEPART(MONTH, NASCIMENTO) AS VARCHAR)+'/'+
CAST(DATEPART(YEAR, NASCIMENTO) AS VARCHAR) AS "NASCIMENTO"
FROM ALUNO
GO

/*	CHARINDEX - RETORNA UM VALOR INTEIRO
	CHARINDEX(O QUE PROCURAR, ONDE, A PARTIR DE(POSIÇÃO))
	CONTAGEM DEFAULT INICIA EM 1
*/

SELECT NOME, CHARINDEX('A', NOME)
FROM ALUNO
GO

SELECT NOME, CHARINDEX('A', NOME, 2)
FROM ALUNO
GO

/* BULK INSERT - IMPORTAÇÃO DE ARQUIVOS */

CREATE TABLE LANCAMENTO_CONTABIL(
	CONTA INT,
	VALOR INT,
	DEB_CRED CHAR(1)
)
GO

SELECT * FROM LANCAMENTO_CONTABIL
GO

/* PODERIA SER USADO EM FIELDTERMINATOR UM ";" PARA INDICAR A COLUNA/FINAL DO CAMPO */
BULK INSERT LANCAMENTO_CONTABIL
FROM 'C:\Users\di_an\OneDrive\Documentos\GitHub\Estudo-Pratica-Geral\SQL\SQL-Server\Arquivos\CONTAS.txt'
WITH
(
	FIRSTROW = 2,
	DATAFILETYPE = 'char',
	FIELDTERMINATOR = '\t',
	ROWTERMINATOR = '\n'
)
GO

delete from LANCAMENTO_CONTABIL

/* ENCONTRANDO SALDO */
SELECT CONTA, VALOR,
CHARINDEX('D', DEB_CRED) AS DEBITO,
CHARINDEX('C', DEB_CRED) AS CREDITO,
CHARINDEX('C', DEB_CRED ) * 2 - 1 AS MULTIPLICADOR
FROM LANCAMENTO_CONTABIL 
GO

SELECT CONTA,
SUM(VALOR * (CHARINDEX('C', DEB_CRED ) * 2 - 1)) AS "SALDO"
FROM LANCAMENTO_CONTABIL
GROUP BY CONTA
GO