/* PROCEDURES */

-- DROPAR A TABELA TELEFONE E RECRIAR PARA TESTES COM PROCEDURES
DROP TABLE TELEFONE
GO

CREATE TABLE PESSOA(
	IDPESSOA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL CHECK (SEXO IN('M','F')), --ENUM
	NASCIMENTO DATE NOT NULL
)
GO

CREATE TABLE TELEFONE(
	IDTELEFONE INT NOT NULL IDENTITY,
	TIPO CHAR(3) NOT NULL CHECK ( TIPO IN('CEL','COM')),
	NUMERO CHAR(10) NOT NULL,
	ID_PESSOA INT
)
GO

ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE_PESSOA
FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
ON DELETE CASCADE
GO

-- PARA DROPAR A CONSTRAINT
ALTER TABLE TELEFONE
DROP CONSTRAINT FK_TELEFONE_PESSOA
GO

INSERT INTO PESSOA (NOME, SEXO, NASCIMENTO)
VALUES
('ANTONIO','M','1981-02-13'),
('DANIEL','M','1985-03-18'),
('CLEIDE','F','1979-10-13'),
('MAFRA','M','1981-02-13')
GO

SELECT @@IDENTITY -- GUARDA O ULTIMO IDENTITY INSERIDO NA SEÇÃO
GO

SELECT * FROM TELEFONE
SELECT * FROM PESSOA
GO

INSERT INTO TELEFONE (TIPO, NUMERO, ID_PESSOA)
VALUES
('CEL','9879008',1),
('COM','8757909',1),
('CEL','9875890',2),
('CEL','9347689',2),
('COM','2998689',3),
('COM','2098978',2),
('CEL','9008679',3)
GO

/* CRIANDO PROCEDURE (ESTÁTICA) */

CREATE PROC SOMA
AS 
	SELECT 10+10 AS SOMA
GO

/* EXECUTANDO A PROCEDURE */

EXEC SOMA
GO

/* CRIANDO PROCEDURE (DINÂMICA) */

CREATE PROC CONTA @NUM1 INT, @NUM2 INT
AS 
	SELECT @NUM1 + @NUM2 AS SOMA
GO

/* EXECUTANDO A PROCEDURE */

EXEC CONTA 190, 20
GO

/* DELETANDO UMA PROCEDURE */
DROP PROC CONTA
GO

/* PROCEDURE EM TABELAS */

SELECT NOME, NUMERO
FROM PESSOA
INNER JOIN TELEFONE
ON IDPESSOA = ID_PESSOA
WHERE TIPO = 'CEL'
GO

/* TRAZER O TELEFONE POR TIPO */

CREATE PROC TELEFONES @TIPO CHAR(3)
AS
	SELECT NOME, NUMERO
	FROM PESSOA
	INNER JOIN TELEFONE
	ON IDPESSOA = ID_PESSOA	
	WHERE TIPO = @TIPO
GO

EXEC TELEFONES 'CEL'
GO

EXEC TELEFONES 'COM'
GO

/* PROCEDURE COM INPUT E PARÂMETROS DE OUTPUT */

SELECT TIPO, COUNT(*) AS QUANTIDADE
FROM TELEFONE
GROUP BY TIPO
GO

CREATE PROCEDURE GETTIPO @TIPO CHAR(3), @CONTADOR INT OUTPUT
AS
	SELECT @CONTADOR = COUNT(*)
	FROM TELEFONE
	WHERE TIPO = @TIPO
GO

/* EXECUTANDO A PROCEDURE */

DECLARE @SAIDA INT
EXEC GETTIPO @TIPO = 'COM', @CONTADOR = @SAIDA OUTPUT
SELECT @SAIDA
GO

-- TAMBÉM PODERIA SER FEITO DESTA FORMA

DECLARE @SAIDA INT
EXEC GETTIPO 'COM', @SAIDA OUTPUT
SELECT @SAIDA AS 'RESULTADO'
GO

/* PROCEDURE DE CADASTRO */

SELECT @@IDENTITY -- GUARDA O ÚLTIMO IDENTITY INSERIDO NA SEÇÃO

CREATE PROCEDURE CADASTRO
	@NOME VARCHAR(30),
	@SEXO CHAR(1),
	@NASCIMENTO DATE,
	@TIPO VARCHAR(3),
	@NUMERO VARCHAR(10)
AS 
	DECLARE
		@FK INT

	INSERT INTO PESSOA
	VALUES
	(@NOME, @SEXO, @NASCIMENTO)

	SET @FK = (SELECT IDPESSOA FROM PESSOA WHERE IDPESSOA = @@IDENTITY)

	INSERT INTO TELEFONE
	VALUES
	(@TIPO, @NUMERO, @FK)
GO

/* EXECUTANDO A PROCEDURE DE CADASTRO */

EXEC CADASTRO 'DIEGO','M','1999-02-12','CEL','9999999'
GO

SELECT * FROM PESSOA
SELECT * FROM TELEFONE
GO

SELECT PESSOA.*, TELEFONE.*
FROM PESSOA
INNER JOIN TELEFONE
ON IDPESSOA = ID_PESSOA
GO