/* TSQL - INTRODRUÇÃO */

/* BLOCO DE EXECUÇÃO */
BEGIN
	PRINT 'PRIMEIRO BLOCO'
END
GO

/* BLOCO DE ATRIBUIÇÃO DE VARIÁVEIS */

-- BLOCO DE DECLARÃO
DECLARE
	@CONTADOR INT

-- BLOCO DE EXECUÇÃO
BEGIN 
	SET @CONTADOR = 5
	PRINT @CONTADOR
END
GO

/* CADA COLUNA, VARIÁVEL LOCAL, EXPRESSÃO E PARÂMETRO POSSUEM UM ATRIBUTO (INT, STRING, BOOLEAN, ETC.) */

DECLARE
	@V_NUMERO NUMERIC(10,2) = 100.52,
	@V_DATA DATETIME = '20230709'

BEGIN
	PRINT 'VALOR NÚMERICO: ' + CAST(@V_NUMERO AS VARCHAR)
	-- GERALMENTE UTILIZADO CONVERT EM CONVERSÃO DE DATAS
	PRINT 'VALOR NÚMERICO: ' + CONVERT(VARCHAR, @V_NUMERO)
	PRINT 'DATA: '+ CAST(@V_DATA AS VARCHAR)
	PRINT 'DATA: ' + CONVERT(VARCHAR, @V_DATA, 121)
	PRINT 'DATA: ' + CONVERT(VARCHAR, @V_DATA, 120)
	-- 105 FORMATAÇÃO PT-BR
	PRINT 'DATA: ' + CONVERT(VARCHAR, @V_DATA, 105)
END
GO


