/* TSQL - INTRODRUÇÃO */

/* BLOCO DE EXECUÇÃO */
BEGIN
	PRINT 'PRIMEIRO BLOCO'
END
GO

/* BLOCO DE ATRIBUIÇÃO DE VARIÁVEIS */

-- BLOCO DE DECLARÃO
DECLARE
	@CONTADOR INT

-- BLOCO DE EXECUÇÃO
BEGIN 
	SET @CONTADOR = 5
	PRINT @CONTADOR
END
GO

/* CADA COLUNA, VARIÁVEL LOCAL, EXPRESSÃO E PARÂMETRO POSSUEM UM ATRIBUTO (INT, STRING, BOOLEAN, ETC.) */

DECLARE
	@V_NUMERO NUMERIC(10,2) = 100.52,
	@V_DATA DATETIME = '20230709'

BEGIN
	PRINT 'VALOR NÚMERICO: ' + CAST(@V_NUMERO AS VARCHAR)
	-- GERALMENTE UTILIZADO CONVERT EM CONVERSÃO DE DATAS
	PRINT 'VALOR NÚMERICO: ' + CONVERT(VARCHAR, @V_NUMERO)
	PRINT 'DATA: '+ CAST(@V_DATA AS VARCHAR)
	PRINT 'DATA: ' + CONVERT(VARCHAR, @V_DATA, 121)
	PRINT 'DATA: ' + CONVERT(VARCHAR, @V_DATA, 120)
	-- 105 FORMATAÇÃO PT-BR
	PRINT 'DATA: ' + CONVERT(VARCHAR, @V_DATA, 105)
END
GO

/* PREPARAÇÃO DO AMBIENTE */

CREATE TABLE CARROS(
	CARRO VARCHAR(20),
	FABRICANTE VARCHAR(30)
)
GO

INSERT INTO CARROS (CARRO, FABRICANTE)
VALUES
('KA','FORD'),
('FIESTA','FORD'),
('PRISMA','FORD'),
('CLIO','RENAULT'),
('SANDERO','RENAULT'),
('CHEVETE','CHEVROLET'),
('OMEGA','CHEVROLET'),
('PALIO','FIAT'),
('DOBLO','FIAT'),
('UNO','FIAT'),
('GOL','VOLKSWAGEN')
GO

/* ATRIBUINDO RESULTADOS A UMA VARIAVEL */

DECLARE
	@V_CONT_FORD INT,
	@V_CONT_FIAT INT

BEGIN
	-- MÉTODO 1 - SELECT RETORNANDO UMA COLUNA, EM UM ÚNICO RESULTADO
	SET @V_CONT_FORD = (SELECT COUNT(*) FROM CARROS
	WHERE FABRICANTE = 'FORD')

	PRINT 'QUANTIDADE FORD: ' + CAST(@V_CONT_FORD AS VARCHAR)

	-- MÉTODO 2 - 
	SELECT @V_CONT_FIAT = COUNT(*) FROM CARROS WHERE FABRICANTE = 'FIAT'

	PRINT 'QUANTIDADE FIAT: ' + CONVERT(VARCHAR, @V_CONT_FIAT)

END
GO

/* BLOCOS IF E ELSE */

DECLARE 
	@NUMERO INT = 5

BEGIN
	
	IF @NUMERO = 5
		PRINT 'TRUE'
	ELSE
		PRINT 'FALSE'

END
GO

/* CASE */

DECLARE
	@CONTADOR INT

BEGIN
	
	SELECT
	CASE -- CASE REPRESENTA UMA COLUNA
		WHEN FABRICANTE = 'FIAT' THEN 'FAIXA 1'
		WHEN FABRICANTE = 'CHEVROLET' THEN 'FAIXA 2'
		ELSE 'OUTRAS FAIXAS'
	END AS "INFORMAÇÕES",
	*
	FROM CARROS
END
GO


/* A EXECUÇÃO É INDEPENDENTE DE DECLARAÇÃO DE VARIÁVEIS (BLOCO ANÔNIMO)*/
BEGIN
	
	SELECT
	CASE -- CASE REPRESENTA UMA COLUNA
		WHEN FABRICANTE = 'FIAT' THEN 'FAIXA 1'
		WHEN FABRICANTE = 'CHEVROLET' THEN 'FAIXA 2'
		ELSE 'OUTRAS FAIXAS'
	END AS "INFORMAÇÕES",
	*
	FROM CARROS
END
GO

/* LOOP - WHILE */

DECLARE 
	@I INT = 1

BEGIN
	
	WHILE (@I <= 15)
	BEGIN
		PRINT 'VALOR DE I = ' + CAST(@I AS VARCHAR)
		SET @I = @I + 1
	END

END
GO


