CREATE DATABASE ESCOLA
GO

USE ESCOLA
GO

CREATE TABLE ALUNO(
	IDALUNO INT IDENTITY(1,1),
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	NASCIMENTO DATE,
	EMAIL VARCHAR(30)
)
GO

CREATE TABLE ENDERECO(
	IDENDERECO INT IDENTITY(1,1),
	BAIRRO VARCHAR(30),
	UF CHAR(2) NOT NULL
	CHECK (UF IN('RJ','SP','MG')),
	ID_ALUNO INT
)
GO

CREATE TABLE TELEFONE(
	IDTELEFONE INT IDENTITY(1,1),
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_ALUNO INT
)
GO

/* Inserts */
INSERT INTO ALUNO(NOME, SEXO, NASCIMENTO, EMAIL)
VALUES
('ANDRE','M','1981/12/09','ANDRE@IG.COM'),
('ANA','F','1978/03/09','ANA@IG.COM'),
('RUI','M','1951/07/09','RUI@IG.COM'),
('JOAO','M','2002/11/09','JOAO@IG.COM')
GO

INSERT INTO ENDERECO(BAIRRO, UF, ID_ALUNO)
VALUES
('FLAMENGO','RJ',1),
('MORUMBI','SP',2),
('CENTRO','MG',3),
('CENTRO','SP',4)
GO

INSERT INTO TELEFONE(TIPO, NUMERO, ID_ALUNO)
VALUES
('CEL','7899889',1),
('RES','4325444',1),
('COM','4354354',2),
('CEL','2344556',2)
GO

/* Constrains Tabela ALUNO */
ALTER TABLE ALUNO
ADD CONSTRAINT CK_SEXO CHECK (SEXO IN('M','F'))
GO

ALTER TABLE ALUNO
ADD CONSTRAINT PK_IDALUNO PRIMARY KEY (IDALUNO)
GO

ALTER TABLE ALUNO
ADD CONSTRAINT UQ_EMAIL UNIQUE (EMAIL)
GO

/* Constraints Tabela ENDERECO */
ALTER TABLE ENDERECO
ADD CONSTRAINT CK_UF CHECK (UF IN('RJ','SP','MG'))
GO

ALTER TABLE ENDERECO
ADD CONSTRAINT UQ_ID_ALUNO UNIQUE (ID_ALUNO)
GO

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(IDALUNO)
GO

/* Constraints Tabela TELEFONE */
ALTER TABLE TELEFONE
ADD CONSTRAINT PK_IDTELEFONE PRIMARY KEY (IDTELEFONE)
GO

ALTER TABLE TELEFONE
ADD CONSTRAINT CK_TIPO CHECK (TIPO IN('RES','COM','TEL'))
GO
